# Jekyll configuration

name: 0x00's blog
title: 0x00's blog
description: 0x00's security blog.

# Url is currently only used only for the RSS feed in feed.xml
url: http://iamsaqibkhans.github.io


# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl:

sidebar:
    twitter: true
    github: true
    slack: false
    recent: false
    tags: true
    archive: true
    
share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: false
  email: false

social:
  twitter: init0x00
  github: iamsaqibkhans
  linkedin: iamsaqibkhans

# Google Analytics key, leave blank to ignore
google_analytics_key: 
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
# disqus: abatchy17-github-io
# comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
